In [ ]:
!pip install torch

Collecting torch
  Downloading torch-2.11.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (29 kB)
Requirement already satisfied: filelock in /opt/anaconda3/lib/python3.13/site-packages (from torch) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/anaconda3/lib/python3.13/site-packages (from torch) (4.12.2)
Requirement already satisfied: setuptools<82 in /opt/anaconda3/lib/python3.13/site-packages (from torch) (72.1.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/anaconda3/lib/python3.13/site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in /opt/anaconda3/lib/python3.13/site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.13/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /opt/anaconda3/lib/python3.13/site-packages (from torch) (2025.3.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jinja2->torch) (3.0.2)
Downloading torch-2.11.0-cp313-cp313-macosx_11_0_arm64.whl (80.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 MB 38.8 MB/s eta 0:00:0000:0100:01
Installing collected packages: torch
Successfully installed torch-2.11.0

In [9]:
!pip install --upgrade --force-reinstall pyarrow datasets

Collecting pyarrow
  Using cached pyarrow-24.0.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (3.0 kB)
Collecting datasets
  Using cached datasets-4.8.5-py3-none-any.whl.metadata (19 kB)
Collecting filelock (from datasets)
  Downloading filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Collecting numpy>=1.17 (from datasets)
  Downloading numpy-2.4.4-cp313-cp313-macosx_14_0_arm64.whl.metadata (6.6 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Using cached dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting pandas (from datasets)
  Downloading pandas-3.0.2-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting requests>=2.32.2 (from datasets)
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting httpx<1.0.0 (from datasets)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting tqdm>=4.66.3 (from datasets)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting xxhash (from datasets)
  Using cached xxhash-3.7.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Using cached multiprocess-0.70.19-py313-none-any.whl.metadata (7.5 kB)
Collecting fsspec<=2026.2.0,>=2023.1.0 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting huggingface-hub<2.0,>=0.25.0 (from datasets)
  Using cached huggingface_hub-1.14.0-py3-none-any.whl.metadata (14 kB)
Collecting packaging (from datasets)
  Downloading packaging-26.2-py3-none-any.whl.metadata (3.5 kB)
Collecting pyyaml>=5.1 (from datasets)
  Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.5-cp313-cp313-macosx_11_0_arm64.whl.metadata (8.1 kB)
Collecting anyio (from httpx<1.0.0->datasets)
  Downloading anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting certifi (from httpx<1.0.0->datasets)
  Downloading certifi-2026.4.22-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1.0.0->datasets)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1.0.0->datasets)
  Downloading idna-3.13-py3-none-any.whl.metadata (8.0 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0->datasets)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached hf_xet-1.5.0-cp37-abi3-macosx_11_0_arm64.whl.metadata (4.9 kB)
Collecting typer>=0.20.0 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading typer-0.25.1-py3-none-any.whl.metadata (15 kB)
Collecting typing-extensions>=4.1.0 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading propcache-0.5.2-cp313-cp313-macosx_11_0_arm64.whl.metadata (16 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading yarl-1.23.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.32.2->datasets)
  Downloading charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl.metadata (40 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.32.2->datasets)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting click>=8.2.1 (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading click-8.3.3-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting python-dateutil>=2.8.2 (from pandas->datasets)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->datasets)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached pyarrow-24.0.0-cp313-cp313-macosx_12_0_arm64.whl (35.0 MB)
Using cached datasets-4.8.5-py3-none-any.whl (528 kB)
Using cached dill-0.4.1-py3-none-any.whl (120 kB)
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached huggingface_hub-1.14.0-py3-none-any.whl (661 kB)
Using cached hf_xet-1.5.0-cp37-abi3-macosx_11_0_arm64.whl (3.8 MB)
Using cached multiprocess-0.70.19-py313-none-any.whl (156 kB)
Downloading aiohttp-3.13.5-cp313-cp313-macosx_11_0_arm64.whl (497 kB)
Downloading multidict-6.7.1-cp313-cp313-macosx_11_0_arm64.whl (43 kB)
Downloading yarl-1.23.0-cp313-cp313-macosx_11_0_arm64.whl (85 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading filelock-3.29.0-py3-none-any.whl (39 kB)
Downloading frozenlist-1.8.0-cp313-cp313-macosx_11_0_arm64.whl (49 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Downloading idna-3.13-py3-none-any.whl (68 kB)
Downloading numpy-2.4.4-cp313-cp313-macosx_14_0_arm64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 49.6 MB/s eta 0:00:00
Downloading packaging-26.2-py3-none-any.whl (100 kB)
Downloading propcache-0.5.2-cp313-cp313-macosx_11_0_arm64.whl (54 kB)
Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl (173 kB)
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl (309 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading certifi-2026.4.22-py3-none-any.whl (135 kB)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Downloading typer-0.25.1-py3-none-any.whl (58 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading click-8.3.3-py3-none-any.whl (110 kB)
Downloading rich-15.0.0-py3-none-any.whl (310 kB)
Downloading pygments-2.20.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 41.3 MB/s eta 0:00:00
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading anyio-4.13.0-py3-none-any.whl (114 kB)
Downloading pandas-3.0.2-cp313-cp313-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 52.5 MB/s eta 0:00:00
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached xxhash-3.7.0-cp313-cp313-macosx_11_0_arm64.whl (30 kB)
Installing collected packages: xxhash, urllib3, typing-extensions, tqdm, six, shellingham, pyyaml, pygments, pyarrow, propcache, packaging, numpy, multidict, mdurl, idna, hf-xet, h11, fsspec, frozenlist, filelock, dill, click, charset_normalizer, certifi, attrs, annotated-doc, aiohappyeyeballs, yarl, requests, python-dateutil, multiprocess, markdown-it-py, httpcore, anyio, aiosignal, rich, pandas, httpx, aiohttp, typer, huggingface-hub, datasets
  Attempting uninstall: xxhash
    Found existing installation: xxhash 3.7.0
    Uninstalling xxhash-3.7.0:
      Successfully uninstalled xxhash-3.7.0
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.3.0
    Uninstalling urllib3-2.3.0:
      Successfully uninstalled urllib3-2.3.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.12.2
    Uninstalling typing_extensions-4.12.2:
      Successfully uninstalled typing_extensions-4.12.2━━━━━━━━━━━  2/42 [typing-extensions]
  Attempting uninstall: tqdm━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/42 [typing-extensions]
    Found existing installation: tqdm 4.67.1━━━━━━━━━━━━━━━━━━  2/42 [typing-extensions]
    Uninstalling tqdm-4.67.1:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/42 [typing-extensions]
      Successfully uninstalled tqdm-4.67.1━━━━━━━━━━━━━━━━━━━━  2/42 [typing-extensions]
  Attempting uninstall: six━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/42 [typing-extensions]
    Found existing installation: six 1.17.0━━━━━━━━━━━━━━━━━━━  2/42 [typing-extensions]
    Uninstalling six-1.17.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/42 [typing-extensions]
      Successfully uninstalled six-1.17.0━━━━━━━━━━━━━━━━━━━━━━━━━  4/42 [six]xtensions]
  Attempting uninstall: shellingham━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/42 [six]
    Found existing installation: shellingham 1.5.0━━━━━━━━━━━━  4/42 [six]
    Uninstalling shellingham-1.5.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/42 [six]
      Successfully uninstalled shellingham-1.5.0━━━━━━━━━━━━━━  4/42 [six]
  Attempting uninstall: pyyaml━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/42 [six]
    Found existing installation: PyYAML 6.0.2━━━━━━━━━━━━━━━━━  4/42 [six]
    Uninstalling PyYAML-6.0.2:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/42 [six]
      Successfully uninstalled PyYAML-6.0.2━━━━━━━━━━━━━━━━━━━  4/42 [six]
  Attempting uninstall: pygments━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/42 [six]
    Found existing installation: Pygments 2.19.1━━━━━━━━━━━━━━  4/42 [six]
    Uninstalling Pygments-2.19.1:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/42 [six]
      Successfully uninstalled Pygments-2.19.1━━━━━━━━━━━━━━━━  4/42 [six]
  Attempting uninstall: pyarrow0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  7/42 [pygments]
    Found existing installation: pyarrow 24.0.0━━━━━━━━━━━━━━━  7/42 [pygments]
    Uninstalling pyarrow-24.0.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  7/42 [pygments]
      Successfully uninstalled pyarrow-24.0.0━━━━━━━━━━━━━━━━━  7/42 [pygments]
  Attempting uninstall: propcachem━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/42 [pyarrow]
    Found existing installation: propcache 0.3.1━━━━━━━━━━━━━━  8/42 [pyarrow]
    Uninstalling propcache-0.3.1:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/42 [pyarrow]
      Successfully uninstalled propcache-0.3.1━━━━━━━━━━━━━━━━  8/42 [pyarrow]
  Attempting uninstall: packaging━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/42 [pyarrow]
    Found existing installation: packaging 24.2━━━━━━━━━━━━━━━  8/42 [pyarrow]
    Uninstalling packaging-24.2:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/42 [pyarrow]
      Successfully uninstalled packaging-24.2━━━━━━━━━━━━━━━━━  8/42 [pyarrow]
  Attempting uninstall: numpym━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/42 [pyarrow]
    Found existing installation: numpy 2.1.3━━━━━━━━━━━━━━━━━━  8/42 [pyarrow]
    Uninstalling numpy-2.1.3:[0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/42 [numpy]
      Successfully uninstalled numpy-2.1.3━━━━━━━━━━━━━━━━━━━━ 11/42 [numpy]
  Attempting uninstall: multidict[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/42 [numpy]
    Found existing installation: multidict 6.1.0━━━━━━━━━━━━━━ 11/42 [numpy]
    Uninstalling multidict-6.1.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/42 [numpy]
      Successfully uninstalled multidict-6.1.0━━━━━━━━━━━━━━━━ 11/42 [numpy]
  Attempting uninstall: mdurl[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/42 [numpy]
    Found existing installation: mdurl 0.1.0━━━━━━━━━━━━━━━━━━ 11/42 [numpy]
    Uninstalling mdurl-0.1.0:[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/42 [numpy]
      Successfully uninstalled mdurl-0.1.0━━━━━━━━━━━━━━━━━━━━ 11/42 [numpy]
  Attempting uninstall: idna━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/42 [numpy]
    Found existing installation: idna 3.7━━━━━━━━━━━━━━━━━━━━━ 11/42 [numpy]
    Uninstalling idna-3.7:0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/42 [numpy]
      Successfully uninstalled idna-3.7━━━━━━━━━━━━━━━━━━━━━━━ 11/42 [numpy]
  Attempting uninstall: hf-xet90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/42 [numpy]
    Found existing installation: hf-xet 1.5.0━━━━━━━━━━━━━━━━━ 11/42 [numpy]
    Uninstalling hf-xet-1.5.0:m╺━━━━━━━━━━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
      Successfully uninstalled hf-xet-1.5.0━━━━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
  Attempting uninstall: h11╺━━━━━━━━━━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
    Found existing installation: h11 0.16.0━━━━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
    Uninstalling h11-0.16.0:━━━━━━━━━━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
      Successfully uninstalled h11-0.16.0━━━━━━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
  Attempting uninstall: fsspec0m━━━━━━━━━━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
    Found existing installation: fsspec 2025.3.2━━━━━━━━━━━━━━ 15/42 [hf-xet]
    Uninstalling fsspec-2025.3.2:[90m━━━━━━━━━━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
      Successfully uninstalled fsspec-2025.3.2━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
  Attempting uninstall: frozenlist90m━━━━━━━━━━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
    Found existing installation: frozenlist 1.5.0━━━━━━━━━━━━━ 15/42 [hf-xet]
    Uninstalling frozenlist-1.5.0:90m━━━━━━━━━━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
      Successfully uninstalled frozenlist-1.5.0━━━━━━━━━━━━━━━ 15/42 [hf-xet]
  Attempting uninstall: filelock━━━━━━━━━━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
    Found existing installation: filelock 3.17.0━━━━━━━━━━━━━━ 15/42 [hf-xet]
    Uninstalling filelock-3.17.0:[90m━━━━━━━━━━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
      Successfully uninstalled filelock-3.17.0━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
  Attempting uninstall: dill━━━━━━━━━━━━━━━━━━━━━━━━━ 15/42 [hf-xet]
    Found existing installation: dill 0.4.190m━━━━━━━━━━━━━━━━━━━━ 20/42 [dill]
    Uninstalling dill-0.4.1:[90m╺━━━━━━━━━━━━━━━━━━━━ 20/42 [dill]
      Successfully uninstalled dill-0.4.1m━━━━━━━━━━━━━━━━━━━━ 20/42 [dill]
  Attempting uninstall: click90m╺━━━━━━━━━━━━━━━━━━━━ 20/42 [dill]
    Found existing installation: click 8.3.1━━━━━━━━━━━━━━━━━━ 20/42 [dill]
    Uninstalling click-8.3.1:90m╺━━━━━━━━━━━━━━━━━━━━ 20/42 [dill]
      Successfully uninstalled click-8.3.1━━━━━━━━━━━━━━━━━━━━ 20/42 [dill]
  Attempting uninstall: charset_normalizer━━━━━━━━━━━━━━━━━━━━ 20/42 [dill]
    Found existing installation: charset-normalizer 3.3.2━━━━━ 20/42 [dill]
    Uninstalling charset-normalizer-3.3.2:━━━━━━━━━━━━━━━━━━━━ 20/42 [dill]
      Successfully uninstalled charset-normalizer-3.3.2━━━━━━━ 20/42 [dill]
  Attempting uninstall: certifim╺━━━━━━━━━━━━━━━━━━━━ 20/42 [dill]
    Found existing installation: certifi 2025.11.12━━━━━━━━━━━ 20/42 [dill]
    Uninstalling certifi-2025.11.12:m━━━━━━━━━━━━━━━━━━━━ 20/42 [dill]
      Successfully uninstalled certifi-2025.11.12━━━━━━━━━━━━━ 20/42 [dill]
  Attempting uninstall: attrs90m╺━━━━━━━━━━━━━━━━━━━━ 20/42 [dill]
    Found existing installation: attrs 24.3.0━━━━━━━━━━━━━━━━━ 20/42 [dill]
    Uninstalling attrs-24.3.0:0m╺━━━━━━━━━━━━━━━━━━━━ 20/42 [dill]
      Successfully uninstalled attrs-24.3.0━━━━━━━━━━━━━━━━━━━ 20/42 [dill]
  Attempting uninstall: annotated-doc1m╸━━━━━━━━━━━━━━━━━ 24/42 [attrs]
    Found existing installation: annotated-doc 0.0.4━━━━━━━━━━ 24/42 [attrs]
    Uninstalling annotated-doc-0.0.4:[0m━━━━━━━━━━━━━━━━━ 24/42 [attrs]
      Successfully uninstalled annotated-doc-0.0.4━━━━━━━━━━━━ 24/42 [attrs]
  Attempting uninstall: aiohappyeyeballs━━━━━━━━━━━━━━━━━ 24/42 [attrs]
    Found existing installation: aiohappyeyeballs 2.4.4━━━━━━━ 24/42 [attrs]
    Uninstalling aiohappyeyeballs-2.4.4:━━━━━━━━━━━━━━━━━ 24/42 [attrs]
      Successfully uninstalled aiohappyeyeballs-2.4.4━━━━━━━━━ 24/42 [attrs]
  Attempting uninstall: yarl0m╸━━━━━━━━━━━━━━━━━ 24/42 [attrs]
    Found existing installation: yarl 1.18.0m━━━━━━━━━━━━━━━━━ 24/42 [attrs]
    Uninstalling yarl-1.18.0:m╸━━━━━━━━━━━━━━━━━ 24/42 [attrs]
      Successfully uninstalled yarl-1.18.090m━━━━━━━━━━━━━━━━━ 24/42 [attrs]
  Attempting uninstall: requests91m╸━━━━━━━━━━━━━━━━━ 24/42 [attrs]
    Found existing installation: requests 2.32.3━━━━━━━━━━━━━━ 24/42 [attrs]
    Uninstalling requests-2.32.3:1m╸━━━━━━━━━━━━━━━━━ 24/42 [attrs]
      Successfully uninstalled requests-2.32.3━━━━━━━━━━━━━━━━ 24/42 [attrs]
  Attempting uninstall: python-dateutilm━━━━━━━━━━━━━━━━━ 24/42 [attrs]
    Found existing installation: python-dateutil 2.9.0.post0━━ 24/42 [attrs]
    Uninstalling python-dateutil-2.9.0.post0:━━━━━━━━━━━━━━━━━ 24/42 [attrs]
      Successfully uninstalled python-dateutil-2.9.0.post0━━━━ 24/42 [attrs]
  Attempting uninstall: multiprocess━━━━━━━━━━━━━━━━━ 24/42 [attrs]
    Found existing installation: multiprocess 0.70.19━━━━━━━━━ 24/42 [attrs]
    Uninstalling multiprocess-0.70.19:0m━━━━━━━━━━━━━━━━━ 24/42 [attrs]
      Successfully uninstalled multiprocess-0.70.19━━━━━━━━━━━ 24/42 [attrs]
  Attempting uninstall: markdown-it-py0m╸━━━━━━━━━━━ 30/42 [multiprocess]
    Found existing installation: markdown-it-py 2.2.0━━━━━━━━━ 30/42 [multiprocess]
    Uninstalling markdown-it-py-2.2.0:91m╸━━━━━━━━━━━ 30/42 [multiprocess]
      Successfully uninstalled markdown-it-py-2.2.0━━━━━━━━━━━ 30/42 [multiprocess]
  Attempting uninstall: httpcore╸━━━━━━━━━━━ 30/42 [multiprocess]
    Found existing installation: httpcore 1.0.9[90m━━━━━━━━━━━ 30/42 [multiprocess]
    Uninstalling httpcore-1.0.9:╸━━━━━━━━━━━ 30/42 [multiprocess]
      Successfully uninstalled httpcore-1.0.9m━━━━━━━━━━━ 30/42 [multiprocess]
  Attempting uninstall: anyio━━━╸━━━━━━━━━━━ 30/42 [multiprocess]
    Found existing installation: anyio 4.7.00m━━━━━━━━━━━ 30/42 [multiprocess]
    Uninstalling anyio-4.7.0:━━━╸━━━━━━━━━━━ 30/42 [multiprocess]
      Successfully uninstalled anyio-4.7.0m╺━━━━━━━━ 33/42 [anyio]ss]
  Attempting uninstall: aiosignal━━╺━━━━━━━━ 33/42 [anyio]
    Found existing installation: aiosignal 1.2.0m━━━━━━━━ 33/42 [anyio]
    Uninstalling aiosignal-1.2.0:━━╺━━━━━━━━ 33/42 [anyio]
      Successfully uninstalled aiosignal-1.2.0[0m━━━━━━━━ 33/42 [anyio]
  Attempting uninstall: rich━━━━━━━╺━━━━━━━━ 33/42 [anyio]
    Found existing installation: rich 13.9.4╺━━━━━━━━ 33/42 [anyio]
    Uninstalling rich-13.9.4:━━━━━━╺━━━━━━━━ 33/42 [anyio]
      Successfully uninstalled rich-13.9.40m╺━━━━━━━━ 33/42 [anyio]
  Attempting uninstall: pandas━━━━━━━━━━━╺━━━━━━ 35/42 [rich]
    Found existing installation: pandas 2.2.3m╺━━━━━━ 35/42 [rich]
    Uninstalling pandas-2.2.3:━━━━━━━╺━━━━━━ 35/42 [rich]
      Successfully uninstalled pandas-2.2.390m╺━━━━━━ 35/42 [rich]
  Attempting uninstall: httpx━━━━━━━━━━━━━╺━━━━━ 36/42 [pandas]
    Found existing installation: httpx 0.28.10m╺━━━━━ 36/42 [pandas]
    Uninstalling httpx-0.28.1:━━━━━━━━╺━━━━━ 36/42 [pandas]

In [6]:
!pip install datasets

Collecting datasets
  Downloading datasets-4.8.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /opt/anaconda3/lib/python3.13/site-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /opt/anaconda3/lib/python3.13/site-packages (from datasets) (2.1.3)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-24.0.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /opt/anaconda3/lib/python3.13/site-packages (from datasets) (2.32.3)
Requirement already satisfied: httpx<1.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /opt/anaconda3/lib/python3.13/site-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.7.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Downloading multiprocess-0.70.19-py313-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.3.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /opt/anaconda3/lib/python3.13/site-packages (from datasets) (1.14.0)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.13/site-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/anaconda3/lib/python3.13/site-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/anaconda3/lib/python3.13/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.11.10)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (4.7.0)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (3.7)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.0)
Requirement already satisfied: typer>=0.20.0 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.12.2)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.18.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: click>=8.2.1 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.0)
Requirement already satisfied: rich>=12.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich>=12.3.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich>=12.3.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.0)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.13/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-4.8.5-py3-none-any.whl (528 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.0/529.0 kB 10.2 MB/s eta 0:00:00
Downloading multiprocess-0.70.19-py313-none-any.whl (156 kB)
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading pyarrow-24.0.0-cp313-cp313-macosx_12_0_arm64.whl (35.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.0/35.0 MB 40.2 MB/s eta 0:00:00a 0:00:01
Downloading xxhash-3.7.0-cp313-cp313-macosx_11_0_arm64.whl (30 kB)
Installing collected packages: xxhash, pyarrow, dill, multiprocess, datasets
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 19.0.0
    Uninstalling pyarrow-19.0.0:
      Successfully uninstalled pyarrow-19.0.0
  Attempting uninstall: dill0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/5 [pyarrow]
    Found existing installation: dill 0.3.8━━━━━━━━━━━━━━━━━━━ 1/5 [pyarrow]
    Uninstalling dill-0.3.8:90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/5 [pyarrow]
      Successfully uninstalled dill-0.3.8━━━━━━━━━━━━━━━━━━━━━ 1/5 [pyarrow]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [datasets]4/5 [datasets]
Successfully installed datasets-4.8.5 dill-0.4.1 multiprocess-0.70.19 pyarrow-24.0.0 xxhash-3.7.0

In [ ]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from transformers import (
    DistilBertTokenizer,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments,
)
from datasets import Dataset

# 1. Load and prep your data
df = pd.read_csv("dataset.csv")
df = df.dropna(subset=["lyrics_cleaned", "parent_genre"])

le = LabelEncoder()
df["label"] = le.fit_transform(df["parent_genre"])
num_labels = len(le.classes_)

train_df, test_df = train_test_split(
    df, test_size=0.2, stratify=df["label"], random_state=42
)
train_df, val_df = train_test_split(
    train_df, test_size=0.1, stratify=train_df["label"], random_state=42
)

# 2. Tokenize
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize(batch):
    return tokenizer(
        batch["lyrics"],
        padding="max_length",
        truncation=True,
        max_length=512,
    )

train_ds = Dataset.from_pandas(train_df[["lyrics", "label"]]).map(tokenize, batched=True)
val_ds   = Dataset.from_pandas(val_df[["lyrics", "label"]]).map(tokenize, batched=True)
test_ds  = Dataset.from_pandas(test_df[["lyrics", "label"]]).map(tokenize, batched=True)

# 3. Load the model with a fresh classification head
model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased", num_labels=num_labels
)

# 4. Train
def compute_metrics(eval_pred):
    from sklearn.metrics import accuracy_score, f1_score
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1_macro": f1_score(labels, preds, average="macro"),
    }

args = TrainingArguments(
    output_dir="./distilbert-genre",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    logging_steps=50,
)

import torch
import torch.nn as nn
import numpy as np
from sklearn.utils.class_weight import compute_class_weight
from transformers import Trainer

# Compute the weights
class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(train_df["label"]),
    y=train_df["label"].values,
)
class_weights = torch.tensor(class_weights, dtype=torch.float)

# Custom Trainer that uses weighted loss
class WeightedTrainer(Trainer):
    def __init__(self, *args, class_weights=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = class_weights

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits
        loss_fct = nn.CrossEntropyLoss(
            weight=self.class_weights.to(logits.device)
        )
        loss = loss_fct(logits, labels)
        return (loss, outputs) if return_outputs else loss

# Use the custom trainer instead of Trainer
trainer = WeightedTrainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics,
    class_weights=class_weights,
)

trainer.train()

/opt/anaconda3/lib/python3.13/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Map:   0%|          | 0/11112 [00:00<?, ? examples/s]

Map:   0%|          | 0/1235 [00:00<?, ? examples/s]

Map:   0%|          | 0/3087 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 1.4303176403045654,
 'eval_accuracy': 0.5114998380304503,
 'eval_f1_macro': 0.35745730957871624}

In [7]:
!pip install 'accelerate>=1.1.0'

Collecting accelerate>=1.1.0
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in /opt/anaconda3/lib/python3.13/site-packages (from accelerate>=1.1.0) (2.4.4)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from accelerate>=1.1.0) (26.2)
Requirement already satisfied: psutil in /opt/anaconda3/lib/python3.13/site-packages (from accelerate>=1.1.0) (5.9.0)
Requirement already satisfied: pyyaml in /opt/anaconda3/lib/python3.13/site-packages (from accelerate>=1.1.0) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from accelerate>=1.1.0) (2.11.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in /opt/anaconda3/lib/python3.13/site-packages (from accelerate>=1.1.0) (1.14.0)
Requirement already satisfied: safetensors>=0.4.3 in /opt/anaconda3/lib/python3.13/site-packages (from accelerate>=1.1.0) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.67.3)
Requirement already satisfied: typer>=0.20.0 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.15.0)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.13.0)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (3.13)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.16.0)
Requirement already satisfied: setuptools<82 in /opt/anaconda3/lib/python3.13/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (72.1.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/anaconda3/lib/python3.13/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in /opt/anaconda3/lib/python3.13/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.4.2)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.13/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.1.0) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich>=13.8.0->typer>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich>=13.8.0->typer>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jinja2->torch>=2.0.0->accelerate>=1.1.0) (3.0.2)
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.13.0